# Generated by Django 6.0.3 on 2026-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_repo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_img', models.ImageField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('linkdin', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('github', models.URLField()),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
