# Generated by Django 6.0.3 on 2026-03-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_college_grade_userprofile_college_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='college_grade',
            new_name='college_location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='school_grade',
            new_name='school_location',
        ),
    ]
