# Generated by Django 6.0.3 on 2026-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_college_grade_userprofile_college_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='media/profile/'),
        ),
    ]
