# Generated by Django 6.0.3 on 2026-03-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_project_details_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(null=True),
        ),
    ]
