# Generated by Django 6.0.3 on 2026-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
